Repository ponylang/http_server, pull requests merged in 2022-02, with the labels that each got.

#41 Add nodoc annotation to test code
  http_server/_test.pony
  http_server/_test_connection_handling.pony
  http_server/_test_headers.pony
  http_server/_test_pipelining.pony
  http_server/_test_reponse.pony
  http_server/_test_request_parser.pony
  http_server/_test_server_error_handling.pony
Labels: discuss during sync

#42 Update to work with Pony 0.47.0
  .release-notes/0.47.0.md
  http_server/_server_connection.pony
  http_server/request_parser.pony
  http_server/session.pony
Labels: changelog - changed, discuss during sync

#43 Update to work with Pony 0.49.0
  .release-notes/49.md
  corral.json
  examples/hello_world/main.pony
  examples/httpserver/httpserver.pony
  examples/raw_tcp/raw_tcp.pony
  examples/sync_httpserver/main.pony
  http_server/_test.pony
  http_server/_test_connection_handling.pony
  http_server/_test_headers.pony
  http_server/_test_pipelining.pony
  http_server/_test_reponse.pony
  http_server/_test_request_parser.pony
  http_server/_test_server_error_handling.pony
  http_server/server.pony
Labels: changelog - fixed, discuss during sync

#44 Update benchmark to work with Pony 0.47.0
  bench/bench.pony
Labels: discuss during sync
